/**
 * Hand-made Bid summary input shared by bid-summary.test.ts and bid-summary-pdf.test.ts: one
 * section, one parapet, an accessory row, two Non-DL lines; no curbs, metals or tear-off.
 */
import type { BidSummaryInput } from "./bid-summary";
import type { SavedBidState } from "./proposal-bid";
import type { ReviewData } from "./review-export";
import type { ReviewLedger } from "./engine/review-ledger";

const state: SavedBidState = {
  roofSystem: "Duro-Last",
  attachment: "mechanical",
  sections: [
    {
      id: "s1",
      name: "Main roof",
      length: 100,
      width: 50,
      deckType: "Steel",
      thickness: 50,
      color: "White",
      fieldLap: 6,
      fastenerOc: 12,
      pullTest: 350,
      perimLengthFt: 0,
      cornerLengthFt: 0,
      enhancementWidthFt: 3,
      perimFastenerOc: 6,
      cornerFastenerOc: 6,
      underlaymentBoard: "",
      layers: [
        {
          board: '1/2" ISO',
          attachment: "mechanical",
          fastenersPerBoard: 0,
          adhesiveName: "",
          substrate: "",
        },
      ],
      edges: [
        {
          side: "A",
          lengthFt: 100,
          isPerimeter: true,
          termination: "T-Bar",
          blockingFt: 0,
          arpSizeIn: 0,
        },
        {
          side: "B",
          lengthFt: 50,
          isPerimeter: false,
          termination: "No Termination",
          blockingFt: 0,
          arpSizeIn: 0,
        },
        {
          side: "C",
          lengthFt: 100,
          isPerimeter: false,
          termination: "No Termination",
          blockingFt: 0,
          arpSizeIn: 0,
        },
        {
          side: "D",
          lengthFt: 50,
          isPerimeter: false,
          termination: "No Termination",
          blockingFt: 0,
          arpSizeIn: 0,
        },
      ],
      sheetSizeLabel: "1500 sf",
      tearOff: false,
      tearOffType: "",
      toThicknessInches: 0,
    },
  ],
  accessories: [
    { description: "Drains — Retrofit drain 4in", price: 120, quantity: 2, laborHoursPerUnit: 1 },
  ],
  nonDlLines: [],
  parapets: [
    {
      id: "p1",
      name: "North wall",
      lengthFt: 100,
      heightBand: '0"-30"',
      deckType: "Wood",
      predrill: false,
      canted: false,
      girthInches: 0,
      pieces: 1,
      verticalInches: 24,
      wallTopInches: 6,
      wallType: 4,
    },
  ],
  curbs: [],
  customer: {
    name: "Acme Storage",
    contact: "Pat Lee",
    projectAddress: "12 Dock Rd",
    notes: "Owner wants a spring start.",
    jobCity: "Springfield",
    jobState: "IL",
    jobZip: "62701",
  },
  markupMode: 2,
  markup: 35,
  laborRate: 50,
  commission: 3,
  taxExempt: false,
  startDate: "2026-10-01",
  buildingType: "Commercial",
};

const review: ReviewData = {
  bidName: "Acme warehouse",
  statusLabel: "Draft",
  membraneMaterial: 6000,
  parapetMaterial: 900,
  curbMaterial: 0,
  metalsMaterial: 0,
  adhesiveMaterial: 0,
  accessoryMaterial: 240,
  underlaymentMaterial: 4250,
  otherMaterial: 300,
  discounts: 0,
  warrantyCost: 0,
  shipping: 500,
  laborCost: 4000,
  subsServices: 0,
  subtotal1: 16190,
  markupLabel: "Gross profit %",
  markupValue: 8717.69,
  subtotal2: 24907.69,
  commissionValue: 747.23,
  perDiemCharge: 0,
  salesTaxValue: 700,
  grandTotal: 26354.92,
  installHours: 40,
  setupHours: 16,
  inspectionHours: 5,
  tearOffHours: 0,
  accessoryHours: 2,
  parapetHours: 12,
  curbHours: 0,
  underlaymentHours: 5,
  ownRateHours: 0,
  totalManDays: 8.89,
  disposalUnits: 0,
  roofSqFt: 5000,
  membraneSqFt: 5600,
};

const ledger: ReviewLedger = {
  purchases: {
    duroLast: [
      { label: "Roof Sections", cost: 6000 },
      { label: "Parapets", cost: 900 },
    ],
    insulation: [{ label: "4x8 ISO", cost: 4250 }],
    nonDuroLast: [{ label: "Wood Blocking", cost: 300 }],
    materials: 11690,
    tax: 700,
    shippingDl: 500,
  },
  labor: {
    duroLast: [{ label: "Roof Sections", cost: 2000, hours: 40 }],
    insulation: [{ label: "4x8 ISO", cost: 250, hours: 5 }],
    nonDuroLast: [],
    setup: { label: "Setup", cost: 800, hours: 16 },
    inspection: { label: "Inspection", cost: 250, hours: 5 },
    tearOff: { label: "Tear Off", cost: 0, hours: 0 },
    totalLabor: { label: "Total Labor", cost: 4000, hours: 80 },
    subcontractors: [],
    services: [],
    totalSubsSvc: 0,
  },
};

export const summaryInput: BidSummaryInput = {
  bidName: "Acme warehouse",
  statusLabel: "Draft",
  state,
  effective: { hoursPerDay: 9, salesTaxRate: 0.0625, taxMaterialOnly: false },
  exportedAt: new Date(2026, 8, 28),
  computed: {
    est: {
      setupHours: 16,
      inspectionHours: 5,
      tearOffLaborHours: 0,
      disposalUnits: 0,
      underlaymentLaborHours: 5,
      parapetLaborHours: 12,
      curbLaborHours: 0,
      laborSubtotal1: 4000,
      roofSqFootage: 5000,
      sqFtTotalMembrane: 5400,
      money: {
        dTotals: { 0: 7140, 4: 7140, 6: 4250, 7: 300, 8: 11690, 9: 500, 10: 4000, 11: 0 },
        grandTotal: 26354.92,
        subtotal1: 16190,
        markupValue: 8717.69,
        subtotal2: 24907.69,
        commissionValue: 747.23,
        perDiemValue: 0,
        totalManDays: 8.89,
        taxCharged: 700,
      },
    },
    ledger,
    review,
    sectionHours: [40],
    underlaymentHoursBySection: { s1: { adjusted: 5, quote: 0 } },
    parapetHoursById: { p1: 12 },
    curbHoursById: {},
    parapetMaterial: 900,
    curbMaterial: 0,
    accessories: {
      lines: [
        {
          screen: "Drains",
          qty: 2,
          name: "Retrofit drain 4in",
          unitCost: 120,
          totalCost: 240,
          hours: 2,
        },
      ],
      totalCost: 240,
      manHours: 2,
    },
    accessoryTotal: 240,
    accessoryLaborHours: 2,
    nonDl: {
      lines: [
        {
          group: "roofEdgeBlocking",
          category: "Roof Edge Blocking",
          item: "2x6 blocking",
          calcQty: 100,
          extraQty: 0,
          qty: 100,
          unitCost: 2,
          materialCost: 200,
          laborPerUnit: 0.05,
          hours: 5,
          laborRate: 40,
          laborCost: 200,
          isCustom: false,
        },
        {
          group: "masonry",
          category: "Masonry",
          item: "Tuckpointing",
          calcQty: 0,
          extraQty: 10,
          qty: 10,
          unitCost: 10,
          materialCost: 100,
          laborPerUnit: 0,
          hours: 0,
          laborRate: 0,
          laborCost: 0,
          isCustom: true,
        },
      ],
      byGroup: {
        roofEdgeBlocking: { material: 200, hours: 5, laborCost: 200 },
        wallBlocking: { material: 0, hours: 0, laborCost: 0 },
        deckMaterials: { material: 0, hours: 0, laborCost: 0 },
        sheetMetal: { material: 0, hours: 0, laborCost: 0 },
        masonry: { material: 100, hours: 0, laborCost: 0 },
        services: { material: 0, hours: 0, laborCost: 0 },
        subcontractors: { material: 0, hours: 0, laborCost: 0 },
        customApps: { material: 0, hours: 0, laborCost: 0 },
        others: { material: 0, hours: 0, laborCost: 0 },
      },
      totalMaterialIncludingServices: 300,
      totalHours: 5,
      totalLaborCost: 200,
      subsCost: 0,
      servicesCost: 0,
    },
    stats: { roofSqFt: 5000, membraneSqFt: 5600, parapetVertSqFt: 200, parapetWallSqFt: 250 },
  },
};
