/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as ProspectRouteImport } from './routes/prospect'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as TakeoffRouteImport } from './routes/takeoff'
import { Route as AdminDuroLastRouteImport } from './routes/admin.duro-last'
import { Route as AdminLaborRouteImport } from './routes/admin.labor'
import { Route as AdminNonDlRouteImport } from './routes/admin.non-dl'
import { Route as AdminPriceImportRouteImport } from './routes/admin.price-import'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ServiceBoardRouteImport } from './routes/service.board'
import { Route as ServiceInvoicesRouteImport } from './routes/service.invoices'
import { Route as ServiceTodayRouteImport } from './routes/service.today'
import { Route as ApiCronRemindersRouteImport } from './routes/api.cron.reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectRoute = ProspectRouteImport.update({
  id: '/prospect',
  path: '/prospect',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeoffRoute = TakeoffRouteImport.update({
  id: '/takeoff',
  path: '/takeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDuroLastRoute = AdminDuroLastRouteImport.update({
  id: '/admin/duro-last',
  path: '/admin/duro-last',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLaborRoute = AdminLaborRouteImport.update({
  id: '/admin/labor',
  path: '/admin/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNonDlRoute = AdminNonDlRouteImport.update({
  id: '/admin/non-dl',
  path: '/admin/non-dl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPriceImportRoute = AdminPriceImportRouteImport.update({
  id: '/admin/price-import',
  path: '/admin/price-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceBoardRoute = ServiceBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ServiceRoute,
} as any)
const ServiceInvoicesRoute = ServiceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ServiceRoute,
} as any)
const ServiceTodayRoute = ServiceTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => ServiceRoute,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bids': typeof BidsRoute
  '/customers': typeof CustomersRoute
  '/estimate': typeof EstimateRoute
  '/followups': typeof FollowupsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/proposal': typeof ProposalRoute
  '/prospect': typeof ProspectRoute
  '/service': typeof ServiceRouteWithChildren
  '/takeoff': typeof TakeoffRoute
  '/admin/duro-last': typeof AdminDuroLastRoute
  '/admin/labor': typeof AdminLaborRoute
  '/admin/non-dl': typeof AdminNonDlRoute
  '/admin/price-import': typeof AdminPriceImportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/service/board': typeof ServiceBoardRoute
  '/service/invoices': typeof ServiceInvoicesRoute
  '/service/today': typeof ServiceTodayRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bids': typeof BidsRoute
  '/customers': typeof CustomersRoute
  '/estimate': typeof EstimateRoute
  '/followups': typeof FollowupsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/proposal': typeof ProposalRoute
  '/prospect': typeof ProspectRoute
  '/service': typeof ServiceRouteWithChildren
  '/takeoff': typeof TakeoffRoute
  '/admin/duro-last': typeof AdminDuroLastRoute
  '/admin/labor': typeof AdminLaborRoute
  '/admin/non-dl': typeof AdminNonDlRoute
  '/admin/price-import': typeof AdminPriceImportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/service/board': typeof ServiceBoardRoute
  '/service/invoices': typeof ServiceInvoicesRoute
  '/service/today': typeof ServiceTodayRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bids': typeof BidsRoute
  '/customers': typeof CustomersRoute
  '/estimate': typeof EstimateRoute
  '/followups': typeof FollowupsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/proposal': typeof ProposalRoute
  '/prospect': typeof ProspectRoute
  '/service': typeof ServiceRouteWithChildren
  '/takeoff': typeof TakeoffRoute
  '/admin/duro-last': typeof AdminDuroLastRoute
  '/admin/labor': typeof AdminLaborRoute
  '/admin/non-dl': typeof AdminNonDlRoute
  '/admin/price-import': typeof AdminPriceImportRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/service/board': typeof ServiceBoardRoute
  '/service/invoices': typeof ServiceInvoicesRoute
  '/service/today': typeof ServiceTodayRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bids'
    | '/customers'
    | '/estimate'
    | '/followups'
    | '/inventory'
    | '/login'
    | '/opportunities'
    | '/proposal'
    | '/prospect'
    | '/service'
    | '/takeoff'
    | '/admin/duro-last'
    | '/admin/labor'
    | '/admin/non-dl'
    | '/admin/price-import'
    | '/admin/settings'
    | '/admin/users'
    | '/service/board'
    | '/service/invoices'
    | '/service/today'
    | '/api/cron/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bids'
    | '/customers'
    | '/estimate'
    | '/followups'
    | '/inventory'
    | '/login'
    | '/opportunities'
    | '/proposal'
    | '/prospect'
    | '/service'
    | '/takeoff'
    | '/admin/duro-last'
    | '/admin/labor'
    | '/admin/non-dl'
    | '/admin/price-import'
    | '/admin/settings'
    | '/admin/users'
    | '/service/board'
    | '/service/invoices'
    | '/service/today'
    | '/api/cron/reminders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bids'
    | '/customers'
    | '/estimate'
    | '/followups'
    | '/inventory'
    | '/login'
    | '/opportunities'
    | '/proposal'
    | '/prospect'
    | '/service'
    | '/takeoff'
    | '/admin/duro-last'
    | '/admin/labor'
    | '/admin/non-dl'
    | '/admin/price-import'
    | '/admin/settings'
    | '/admin/users'
    | '/service/board'
    | '/service/invoices'
    | '/service/today'
    | '/api/cron/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BidsRoute: typeof BidsRoute
  CustomersRoute: typeof CustomersRoute
  EstimateRoute: typeof EstimateRoute
  FollowupsRoute: typeof FollowupsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProposalRoute: typeof ProposalRoute
  ProspectRoute: typeof ProspectRoute
  ServiceRoute: typeof ServiceRouteWithChildren
  TakeoffRoute: typeof TakeoffRoute
  AdminDuroLastRoute: typeof AdminDuroLastRoute
  AdminLaborRoute: typeof AdminLaborRoute
  AdminNonDlRoute: typeof AdminNonDlRoute
  AdminPriceImportRoute: typeof AdminPriceImportRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospect': {
      id: '/prospect'
      path: '/prospect'
      fullPath: '/prospect'
      preLoaderRoute: typeof ProspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takeoff': {
      id: '/takeoff'
      path: '/takeoff'
      fullPath: '/takeoff'
      preLoaderRoute: typeof TakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/duro-last': {
      id: '/admin/duro-last'
      path: '/admin/duro-last'
      fullPath: '/admin/duro-last'
      preLoaderRoute: typeof AdminDuroLastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/labor': {
      id: '/admin/labor'
      path: '/admin/labor'
      fullPath: '/admin/labor'
      preLoaderRoute: typeof AdminLaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/non-dl': {
      id: '/admin/non-dl'
      path: '/admin/non-dl'
      fullPath: '/admin/non-dl'
      preLoaderRoute: typeof AdminNonDlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/price-import': {
      id: '/admin/price-import'
      path: '/admin/price-import'
      fullPath: '/admin/price-import'
      preLoaderRoute: typeof AdminPriceImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/board': {
      id: '/service/board'
      path: '/board'
      fullPath: '/service/board'
      preLoaderRoute: typeof ServiceBoardRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/service/invoices': {
      id: '/service/invoices'
      path: '/invoices'
      fullPath: '/service/invoices'
      preLoaderRoute: typeof ServiceInvoicesRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/service/today': {
      id: '/service/today'
      path: '/today'
      fullPath: '/service/today'
      preLoaderRoute: typeof ServiceTodayRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServiceRouteChildren {
  ServiceBoardRoute: typeof ServiceBoardRoute
  ServiceInvoicesRoute: typeof ServiceInvoicesRoute
  ServiceTodayRoute: typeof ServiceTodayRoute
}

const ServiceRouteChildren: ServiceRouteChildren = {
  ServiceBoardRoute: ServiceBoardRoute,
  ServiceInvoicesRoute: ServiceInvoicesRoute,
  ServiceTodayRoute: ServiceTodayRoute,
}

const ServiceRouteWithChildren =
  ServiceRoute._addFileChildren(ServiceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BidsRoute: BidsRoute,
  CustomersRoute: CustomersRoute,
  EstimateRoute: EstimateRoute,
  FollowupsRoute: FollowupsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProposalRoute: ProposalRoute,
  ProspectRoute: ProspectRoute,
  ServiceRoute: ServiceRouteWithChildren,
  TakeoffRoute: TakeoffRoute,
  AdminDuroLastRoute: AdminDuroLastRoute,
  AdminLaborRoute: AdminLaborRoute,
  AdminNonDlRoute: AdminNonDlRoute,
  AdminPriceImportRoute: AdminPriceImportRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
