/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewBidRouteImport } from './routes/new-bid'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as AdminDuroLastRouteImport } from './routes/admin.duro-last'
import { Route as AdminLaborRouteImport } from './routes/admin.labor'
import { Route as AdminNonDlRouteImport } from './routes/admin.non-dl'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewBidRoute = NewBidRouteImport.update({
  id: '/new-bid',
  path: '/new-bid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDuroLastRoute = AdminDuroLastRouteImport.update({
  id: '/admin/duro-last',
  path: '/admin/duro-last',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLaborRoute = AdminLaborRouteImport.update({
  id: '/admin/labor',
  path: '/admin/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNonDlRoute = AdminNonDlRouteImport.update({
  id: '/admin/non-dl',
  path: '/admin/non-dl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bids': typeof BidsRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/new-bid': typeof NewBidRoute
  '/proposal': typeof ProposalRoute
  '/admin/duro-last': typeof AdminDuroLastRoute
  '/admin/labor': typeof AdminLaborRoute
  '/admin/non-dl': typeof AdminNonDlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bids': typeof BidsRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/new-bid': typeof NewBidRoute
  '/proposal': typeof ProposalRoute
  '/admin/duro-last': typeof AdminDuroLastRoute
  '/admin/labor': typeof AdminLaborRoute
  '/admin/non-dl': typeof AdminNonDlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bids': typeof BidsRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/new-bid': typeof NewBidRoute
  '/proposal': typeof ProposalRoute
  '/admin/duro-last': typeof AdminDuroLastRoute
  '/admin/labor': typeof AdminLaborRoute
  '/admin/non-dl': typeof AdminNonDlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bids'
    | '/estimate'
    | '/login'
    | '/new-bid'
    | '/proposal'
    | '/admin/duro-last'
    | '/admin/labor'
    | '/admin/non-dl'
    | '/admin/settings'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bids'
    | '/estimate'
    | '/login'
    | '/new-bid'
    | '/proposal'
    | '/admin/duro-last'
    | '/admin/labor'
    | '/admin/non-dl'
    | '/admin/settings'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bids'
    | '/estimate'
    | '/login'
    | '/new-bid'
    | '/proposal'
    | '/admin/duro-last'
    | '/admin/labor'
    | '/admin/non-dl'
    | '/admin/settings'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BidsRoute: typeof BidsRoute
  EstimateRoute: typeof EstimateRoute
  LoginRoute: typeof LoginRoute
  NewBidRoute: typeof NewBidRoute
  ProposalRoute: typeof ProposalRoute
  AdminDuroLastRoute: typeof AdminDuroLastRoute
  AdminLaborRoute: typeof AdminLaborRoute
  AdminNonDlRoute: typeof AdminNonDlRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-bid': {
      id: '/new-bid'
      path: '/new-bid'
      fullPath: '/new-bid'
      preLoaderRoute: typeof NewBidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/duro-last': {
      id: '/admin/duro-last'
      path: '/admin/duro-last'
      fullPath: '/admin/duro-last'
      preLoaderRoute: typeof AdminDuroLastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/labor': {
      id: '/admin/labor'
      path: '/admin/labor'
      fullPath: '/admin/labor'
      preLoaderRoute: typeof AdminLaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/non-dl': {
      id: '/admin/non-dl'
      path: '/admin/non-dl'
      fullPath: '/admin/non-dl'
      preLoaderRoute: typeof AdminNonDlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BidsRoute: BidsRoute,
  EstimateRoute: EstimateRoute,
  LoginRoute: LoginRoute,
  NewBidRoute: NewBidRoute,
  ProposalRoute: ProposalRoute,
  AdminDuroLastRoute: AdminDuroLastRoute,
  AdminLaborRoute: AdminLaborRoute,
  AdminNonDlRoute: AdminNonDlRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
