-- Item numbers come from the Duro-Last price workbook ONLY (owner, 2026-09-23): the legacy
-- Bid-Advantage "Part #" values had not been updated in years. Every mapping whose number is not
-- on the workbook's "Price List" sheet (13,506 items) is dropped — 199 rows, all legacy-seeded,
-- none ever touched by a price import. The 229 mappings whose numbers ARE on the workbook stay.
-- Catalog prices and the screens' own Part # columns are untouched (row keys depend on them).
-- Products left without a number get one from the Import price sheet page's gap suggestions,
-- confirmed by the admin. A ledger entry's stamped item_no that no longer maps is cleared.
delete from public.catalog_item_numbers
where (item_no, screen_id, row_label, price_col) in (
  ('1107', 'duro_last:adhesives', 'Duro-Fleece Adhesive(2-boxes)', 'price'),
  ('1106', 'duro_last:adhesives', 'Duro-Fleece Adhesive(cartridge)', 'price'),
  ('1109', 'duro_last:adhesives', 'Duro-Grip Adhesive(CR-20)', 'price'),
  ('1105', 'duro_last:adhesives', 'Millenium One Step', 'price'),
  ('1130', 'duro_last:adhesives', 'Millenium PG1 Boxes', 'price'),
  ('1108', 'duro_last:adhesives', 'OlyBond500 Bag-in-Box', 'price'),
  ('1106', 'duro_last:adhesives', 'OlyBond500 SpotShot', 'price'),
  ('1112-010', 'duro_last:adhesives', 'Solvent Based Adhesive', 'price'),
  ('1111', 'duro_last:adhesives', 'Water Based Adhesive', 'price'),
  ('1536H', 'duro_last:cdr_rings', '2 1/2" Drain Ring', 'Price'),
  ('1536', 'duro_last:cdr_rings', '2" Drain Rings', 'Price'),
  ('1537H', 'duro_last:cdr_rings', '3 1/2" Drain Rings', 'Price'),
  ('1537', 'duro_last:cdr_rings', '3" Drain Rings', 'Price'),
  ('1538H', 'duro_last:cdr_rings', '4 1/2" Drain Rings', 'Price'),
  ('1538', 'duro_last:cdr_rings', '4" Drain Rings', 'Price'),
  ('1539H', 'duro_last:cdr_rings', '5 1/2" Drain Rings', 'Price'),
  ('1539', 'duro_last:cdr_rings', '5" Drain Rings', 'Price'),
  ('1540H', 'duro_last:cdr_rings', '6 1/2" Drain Rings', 'Price'),
  ('1540', 'duro_last:cdr_rings', '6" Drain Rings', 'Price'),
  ('1541H', 'duro_last:cdr_rings', '7 1/2" Drain Rings', 'Price'),
  ('1541', 'duro_last:cdr_rings', '7" Drain Rings', 'Price'),
  ('1542', 'duro_last:cdr_rings', '8" Drain Rings', 'Price'),
  ('1336', 'duro_last:conduit_washers', '1" Conduit Washer', 'Price'),
  ('1338', 'duro_last:conduit_washers', '1/2" Conduit Washer', 'Price'),
  ('1337', 'duro_last:conduit_washers', '3/4" Conduit Washer', 'Price'),
  ('1830', 'duro_last:drain_boot_accessories', 'Dome Strainer', 'Price'),
  ('1220', 'duro_last:drip_edge', 'Drip Edge 2"', 'White Price'),
  ('1228', 'duro_last:drip_edge', 'Drip Edge 2" Clip', 'White Price'),
  ('1558', 'duro_last:drip_edge', 'Drip Edge 2" Corner', 'White Price'),
  ('1583', 'duro_last:drip_edge', 'Drip Edge 4"', 'White Price'),
  ('1584', 'duro_last:drip_edge', 'Drip Edge 4" Clip', 'White Price'),
  ('1585', 'duro_last:drip_edge', 'Drip Edge 4" Corner', 'White Price'),
  ('2537', 'duro_last:facia_bars_vinyl_covers', 'Metal Cover [2537]', 'Price'),
  ('2543', 'duro_last:facia_bars_vinyl_covers', 'Metal Cover [2543]', 'Price'),
  ('2517', 'duro_last:facia_bars_vinyl_covers', 'Metal Inside Corner [2517]', 'Price'),
  ('2547', 'duro_last:facia_bars_vinyl_covers', 'Metal Inside Corner [2547]', 'Price'),
  ('2515', 'duro_last:facia_bars_vinyl_covers', 'Metal Outside Corner [2515]', 'Price'),
  ('2545', 'duro_last:facia_bars_vinyl_covers', 'Metal Outside Corner [2545]', 'Price'),
  ('1278-001', 'duro_last:fasteners_and_bits', '1 1/2" [Collated Screws]', 'Price/Box'),
  ('1361', 'duro_last:fasteners_and_bits', '1 1/2" [Drill Point]', 'Price/Box'),
  ('1620', 'duro_last:fasteners_and_bits', '1 1/2" [Nail]', 'Price/Box'),
  ('RN001', 'duro_last:fasteners_and_bits', '1 1/2" [Roofing Nails]', 'Price/Box'),
  ('1442', 'duro_last:fasteners_and_bits', '1 1/2" [Spade]', 'Price/Box'),
  ('1470', 'duro_last:fasteners_and_bits', '1 1/4" [Concrete Screw]', 'Price/Box'),
  ('1444', 'duro_last:fasteners_and_bits', '1 1/4" [Hex Head]', 'Price/Box'),
  ('1471', 'duro_last:fasteners_and_bits', '1 3/4"', 'Price/Box'),
  ('1270', 'duro_last:fasteners_and_bits', '1/2"x10" SDS', 'Price/Box'),
  ('1272', 'duro_last:fasteners_and_bits', '1/2"x12" Straight', 'Price/Box'),
  ('1269', 'duro_last:fasteners_and_bits', '1/2"x6" SDS', 'Price/Box'),
  ('1271', 'duro_last:fasteners_and_bits', '1/2"x6" Straight', 'Price/Box'),
  ('1637', 'duro_last:fasteners_and_bits', '1/4"x12" TE-CX', 'Price/Box'),
  ('1734', 'duro_last:fasteners_and_bits', '1/4"x4" TE-CX', 'Price/Box'),
  ('1735', 'duro_last:fasteners_and_bits', '1/4"x6" TE-CX', 'Price/Box'),
  ('1736', 'duro_last:fasteners_and_bits', '1/4"x8" TE-CX', 'Price/Box'),
  ('1485', 'duro_last:fasteners_and_bits', '10" [Concrete Screw]', 'Price/Box'),
  ('1374', 'duro_last:fasteners_and_bits', '10" [Drill Point]', 'Price/Box'),
  ('1628-010', 'duro_last:fasteners_and_bits', '10" [Nail]', 'Price/Box'),
  ('NTB16', 'duro_last:fasteners_and_bits', '10" [NTB]', 'Price/Box'),
  ('1254', 'duro_last:fasteners_and_bits', '10" [Spade]', 'Price/Box'),
  ('1386', 'duro_last:fasteners_and_bits', '10" [XHD]', 'Price/Box'),
  ('1486', 'duro_last:fasteners_and_bits', '11" [Concrete Screw]', 'Price/Box'),
  ('1375', 'duro_last:fasteners_and_bits', '11" [Drill Point]', 'Price/Box'),
  ('1628-011', 'duro_last:fasteners_and_bits', '11" [Nail]', 'Price/Box'),
  ('1255', 'duro_last:fasteners_and_bits', '11" [Spade]', 'Price/Box'),
  ('1387', 'duro_last:fasteners_and_bits', '11" [XHD]', 'Price/Box'),
  ('1487', 'duro_last:fasteners_and_bits', '12" [Concrete Screw]', 'Price/Box'),
  ('1376', 'duro_last:fasteners_and_bits', '12" [Drill Point]', 'Price/Box'),
  ('1628-012', 'duro_last:fasteners_and_bits', '12" [Nail]', 'Price/Box'),
  ('1256', 'duro_last:fasteners_and_bits', '12" [Spade]', 'Price/Box'),
  ('1388', 'duro_last:fasteners_and_bits', '12" [XHD]', 'Price/Box'),
  ('1257', 'duro_last:fasteners_and_bits', '14"', 'Price/Box'),
  ('1258', 'duro_last:fasteners_and_bits', '16"', 'Price/Box'),
  ('1259', 'duro_last:fasteners_and_bits', '18"', 'Price/Box'),
  ('1363', 'duro_last:fasteners_and_bits', '2 1/2" [Drill Point]', 'Price/Box'),
  ('1622', 'duro_last:fasteners_and_bits', '2 1/2" [Nail]', 'Price/Box'),
  ('NTB01', 'duro_last:fasteners_and_bits', '2 1/2" [NTB]', 'Price/Box'),
  ('1456', 'duro_last:fasteners_and_bits', '2 1/2" [Spade]', 'Price/Box'),
  ('1472', 'duro_last:fasteners_and_bits', '2 1/4"', 'Price/Box'),
  ('1473', 'duro_last:fasteners_and_bits', '2 3/4" [Concrete Screw]', 'Price/Box'),
  ('PL1', 'duro_last:fasteners_and_bits', '2 3/4" [Purlin]', 'Price/Box'),
  ('1362', 'duro_last:fasteners_and_bits', '2" [Drill Point]', 'Price/Box'),
  ('1621', 'duro_last:fasteners_and_bits', '2" [Nail]', 'Price/Box'),
  ('NTB15', 'duro_last:fasteners_and_bits', '2" [NTB]', 'Price/Box'),
  ('1446', 'duro_last:fasteners_and_bits', '2" [Spade]', 'Price/Box'),
  ('1299', 'duro_last:fasteners_and_bits', '2" Barbed Steel', 'Price/Box'),
  ('1305P', 'duro_last:fasteners_and_bits', '2" Poly Plates', 'Price/Box'),
  ('1260', 'duro_last:fasteners_and_bits', '20"', 'Price/Box'),
  ('1365', 'duro_last:fasteners_and_bits', '3 1/2" [Drill Point]', 'Price/Box'),
  ('1624', 'duro_last:fasteners_and_bits', '3 1/2" [Nail]', 'Price/Box'),
  ('NTB03', 'duro_last:fasteners_and_bits', '3 1/2" [NTB]', 'Price/Box'),
  ('1457', 'duro_last:fasteners_and_bits', '3 1/2" [Spade]', 'Price/Box'),
  ('1474', 'duro_last:fasteners_and_bits', '3 1/4"', 'Price/Box'),
  ('1475', 'duro_last:fasteners_and_bits', '3 3/4" [Concrete Screw]', 'Price/Box'),
  ('PL2', 'duro_last:fasteners_and_bits', '3 3/4" [Purlin]', 'Price/Box'),
  ('1364', 'duro_last:fasteners_and_bits', '3" [Drill Point]', 'Price/Box'),
  ('1623', 'duro_last:fasteners_and_bits', '3" [Nail]', 'Price/Box'),
  ('NTB02', 'duro_last:fasteners_and_bits', '3" [NTB]', 'Price/Box'),
  ('1447', 'duro_last:fasteners_and_bits', '3" [Spade]', 'Price/Box'),
  ('1305I', 'duro_last:fasteners_and_bits', '3" Insulation Plates', 'Price/Box'),
  ('1300S', 'duro_last:fasteners_and_bits', '3" Square Steel', 'Price/Box'),
  ('1732', 'duro_last:fasteners_and_bits', '3/16"x12" TE-CX', 'Price/Box'),
  ('1733', 'duro_last:fasteners_and_bits', '3/16"x16" TE-CX', 'Price/Box'),
  ('1730', 'duro_last:fasteners_and_bits', '3/16"x6 1/2" TE-CX', 'Price/Box'),
  ('1731', 'duro_last:fasteners_and_bits', '3/16"x8" TE-CX', 'Price/Box'),
  ('1367', 'duro_last:fasteners_and_bits', '4 1/2" [Drill Point]', 'Price/Box'),
  ('1626', 'duro_last:fasteners_and_bits', '4 1/2" [Nail]', 'Price/Box'),
  ('NTB05', 'duro_last:fasteners_and_bits', '4 1/2" [NTB]', 'Price/Box'),
  ('1458', 'duro_last:fasteners_and_bits', '4 1/2" [Spade]', 'Price/Box'),
  ('1476', 'duro_last:fasteners_and_bits', '4 1/4"', 'Price/Box'),
  ('PL3', 'duro_last:fasteners_and_bits', '4 3/4"', 'Price/Box'),
  ('1366', 'duro_last:fasteners_and_bits', '4" [Drill Point]', 'Price/Box'),
  ('1625', 'duro_last:fasteners_and_bits', '4" [Nail]', 'Price/Box'),
  ('NTB04', 'duro_last:fasteners_and_bits', '4" [NTB]', 'Price/Box'),
  ('1448', 'duro_last:fasteners_and_bits', '4" [Spade]', 'Price/Box'),
  ('1380', 'duro_last:fasteners_and_bits', '4" [XHD]', 'Price/Box'),
  ('1478', 'duro_last:fasteners_and_bits', '5 1/2" [Concrete Screw]', 'Price/Box'),
  ('1369', 'duro_last:fasteners_and_bits', '5 1/2" [Drill Point]', 'Price/Box'),
  ('1619', 'duro_last:fasteners_and_bits', '5 1/2" [Nail]', 'Price/Box'),
  ('NTB07', 'duro_last:fasteners_and_bits', '5 1/2" [NTB]', 'Price/Box'),
  ('1459', 'duro_last:fasteners_and_bits', '5 1/2" [Spade]', 'Price/Box'),
  ('PL4', 'duro_last:fasteners_and_bits', '5 3/4"', 'Price/Box'),
  ('1477', 'duro_last:fasteners_and_bits', '5" [Concrete Screw]', 'Price/Box'),
  ('1368', 'duro_last:fasteners_and_bits', '5" [Drill Point]', 'Price/Box'),
  ('1627', 'duro_last:fasteners_and_bits', '5" [Nail]', 'Price/Box'),
  ('NTB06', 'duro_last:fasteners_and_bits', '5" [NTB]', 'Price/Box'),
  ('1449', 'duro_last:fasteners_and_bits', '5" [Spade]', 'Price/Box'),
  ('1381', 'duro_last:fasteners_and_bits', '5" [XHD]', 'Price/Box'),
  ('1480', 'duro_last:fasteners_and_bits', '6 1/2" [Concrete Screw]', 'Price/Box'),
  ('NTB09', 'duro_last:fasteners_and_bits', '6 1/2" [NTB]', 'Price/Box'),
  ('PL5', 'duro_last:fasteners_and_bits', '6 3/4"', 'Price/Box'),
  ('1479', 'duro_last:fasteners_and_bits', '6" [Concrete Screw]', 'Price/Box'),
  ('1370', 'duro_last:fasteners_and_bits', '6" [Drill Point]', 'Price/Box'),
  ('1628', 'duro_last:fasteners_and_bits', '6" [Nail]', 'Price/Box'),
  ('NTB08', 'duro_last:fasteners_and_bits', '6" [NTB]', 'Price/Box'),
  ('1450', 'duro_last:fasteners_and_bits', '6" [Spade]', 'Price/Box'),
  ('1382', 'duro_last:fasteners_and_bits', '6" [XHD]', 'Price/Box'),
  ('1482', 'duro_last:fasteners_and_bits', '7 1/2" [Concrete Screw]', 'Price/Box'),
  ('NTB11', 'duro_last:fasteners_and_bits', '7 1/2" [NTB]', 'Price/Box'),
  ('PL6', 'duro_last:fasteners_and_bits', '7 3/4"', 'Price/Box'),
  ('1481', 'duro_last:fasteners_and_bits', '7" [Concrete Screw]', 'Price/Box'),
  ('1371', 'duro_last:fasteners_and_bits', '7" [Drill Point]', 'Price/Box'),
  ('1638', 'duro_last:fasteners_and_bits', '7" [Nail]', 'Price/Box'),
  ('NTB10', 'duro_last:fasteners_and_bits', '7" [NTB]', 'Price/Box'),
  ('1451', 'duro_last:fasteners_and_bits', '7" [Spade]', 'Price/Box'),
  ('1383', 'duro_last:fasteners_and_bits', '7" [XHD]', 'Price/Box'),
  ('1642', 'duro_last:fasteners_and_bits', '7/16"x12" SDS', 'Price/Box'),
  ('1641', 'duro_last:fasteners_and_bits', '7/16"x6" SDS', 'Price/Box'),
  ('1267', 'duro_last:fasteners_and_bits', '7/16"x6" Straight', 'Price/Box'),
  ('1637', 'duro_last:fasteners_and_bits', '7/32"x12" Straight', 'Price/Box'),
  ('NTB13', 'duro_last:fasteners_and_bits', '8 1/2" [NTB]', 'Price/Box'),
  ('1483', 'duro_last:fasteners_and_bits', '8" [Concrete Screw]', 'Price/Box'),
  ('1372', 'duro_last:fasteners_and_bits', '8" [Drill Point]', 'Price/Box'),
  ('1639', 'duro_last:fasteners_and_bits', '8" [Nail]', 'Price/Box'),
  ('NTB12', 'duro_last:fasteners_and_bits', '8" [NTB]', 'Price/Box'),
  ('1452', 'duro_last:fasteners_and_bits', '8" [Spade]', 'Price/Box'),
  ('1384', 'duro_last:fasteners_and_bits', '8" [XHD]', 'Price/Box'),
  ('1484', 'duro_last:fasteners_and_bits', '9" [Concrete Screw]', 'Price/Box'),
  ('1373', 'duro_last:fasteners_and_bits', '9" [Drill Point]', 'Price/Box'),
  ('1628-009', 'duro_last:fasteners_and_bits', '9" [Nail]', 'Price/Box'),
  ('NTB14', 'duro_last:fasteners_and_bits', '9" [NTB]', 'Price/Box'),
  ('1253', 'duro_last:fasteners_and_bits', '9" [Spade]', 'Price/Box'),
  ('1385', 'duro_last:fasteners_and_bits', '9" [XHD]', 'Price/Box'),
  ('NTB17', 'duro_last:fasteners_and_bits', 'Bit (Hex Driver)', 'Price/Box'),
  ('1306', 'duro_last:fasteners_and_bits', 'Induction Welding Plates', 'Price/Box'),
  ('1241', 'duro_last:fasteners_and_bits', 'Metal Anchors', 'Price/Box'),
  ('1304', 'duro_last:fasteners_and_bits', 'Metal Cleat Plates', 'Price/Box'),
  ('1226', 'duro_last:gravel_stops', 'Gravel Stop 2"', 'White Price'),
  ('1613', 'duro_last:gravel_stops', 'Gravel Stop 2" Clip', 'White Price'),
  ('1614', 'duro_last:gravel_stops', 'Gravel Stop 2" Corner', 'White Price'),
  ('2525', 'duro_last:gravel_stops', 'Gravel Stop 2" Cover', 'White Price'),
  ('2529', 'duro_last:gravel_stops', 'Gravel Stop 2" Inside Corner', 'White Price'),
  ('2527', 'duro_last:gravel_stops', 'Gravel Stop 2" Outside Corner', 'White Price'),
  ('1587', 'duro_last:gravel_stops', 'Gravel Stop 4"', 'White Price'),
  ('1588', 'duro_last:gravel_stops', 'Gravel Stop 4" Clip', 'White Price'),
  ('1589', 'duro_last:gravel_stops', 'Gravel Stop 4" Corner', 'White Price'),
  ('2554', 'duro_last:gravel_stops', 'Gravel Stop 4" Cover', 'White Price'),
  ('2556', 'duro_last:gravel_stops', 'Gravel Stop 4" Inside Corner', 'White Price'),
  ('2555', 'duro_last:gravel_stops', 'Gravel Stop 4" Outside Corner', 'White Price'),
  ('1001', 'duro_last:membrane_accs', 'ARP (SqFt)', 'Price/Package'),
  ('1115', 'duro_last:sealants', 'Duro-Caulk - Bronze', 'Price'),
  ('1114', 'duro_last:sealants', 'Duro-Caulk - Gray', 'Price'),
  ('1116B', 'duro_last:sealants', 'Duro-Caulk - Tan', 'Price'),
  ('1116', 'duro_last:sealants', 'Duro-Caulk - White', 'Price'),
  ('1138', 'duro_last:sealants', 'Duro-Caulk Plus - Tan', 'Price'),
  ('1125', 'duro_last:sealants', 'Paraseal - Bronze', 'Price'),
  ('1124', 'duro_last:sealants', 'Paraseal - Gray', 'Price'),
  ('1126B', 'duro_last:sealants', 'Paraseal - Tan', 'Price'),
  ('1126', 'duro_last:sealants', 'Paraseal - White', 'Price'),
  ('1121', 'duro_last:sealants', 'Pitch Pocket Filler (10.2 oz)', 'Price'),
  ('1122', 'duro_last:sealants', 'Pitch Pocket Filler (30 oz)', 'Price'),
  ('1119T', 'duro_last:sealants', 'Tab Sealer', 'Price'),
  ('1225G', 'duro_last:termination_bars', 'Gray', 'Price'),
  ('1225B', 'duro_last:termination_bars', 'Tan', 'Price'),
  ('1225', 'duro_last:termination_bars', 'White', 'Price'),
  ('1084', 'duro_last:walk_pads_wall_vents', '30" x 60" Gray - Walk Pad', 'Price'),
  ('1085', 'duro_last:walk_pads_wall_vents', '60" x 60" Gray - Walk Pad', 'Price'),
  ('1235B', 'duro_last:walk_pads_wall_vents', 'Gray Parapet Wall Vent', 'Price'),
  ('1235G', 'duro_last:walk_pads_wall_vents', 'Tan Parapet Wall Vent', 'Price'),
  ('1235', 'duro_last:walk_pads_wall_vents', 'White Parapet Wall Vent', 'Price')
);

update public.inventory_movements m
set item_no = null
where m.item_no is not null
  and not exists (
    select 1 from public.catalog_item_numbers c
    where c.item_no = m.item_no and c.screen_id = m.screen_id
      and c.row_label = m.row_label and c.price_col = m.price_col
  );
