-- Phase 2 (part 2f): Non-Duro-Last Pricing (8 screens) + reusable pricing_catalog table.
-- Idempotent. RLS: authenticated read, admin-only write.

create table if not exists public.pricing_catalog (
  id text primary key,
  branch text not null,
  category text not null,
  data jsonb not null default '{}'::jsonb,
  sort integer not null default 0
);
alter table public.pricing_catalog enable row level security;
revoke all on public.pricing_catalog from anon;
drop policy if exists pricing_catalog_read on public.pricing_catalog;
create policy pricing_catalog_read on public.pricing_catalog for select to authenticated using (true);
drop policy if exists pricing_catalog_write on public.pricing_catalog;
create policy pricing_catalog_write on public.pricing_catalog for all to authenticated using (public.is_admin()) with check (public.is_admin());
insert into public.pricing_catalog (id, branch, category, data, sort)
select * from (values
  ('non_dl:roof_edge_blocking','non_dl','Roof Edge Blocking','{"columns": ["Description", "Price", "LaborPerUnit", "Labor Rate"], "rows": [{"Description": "½\" Wood Blocking", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "¾\" Wood Blocking", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "5/4\" Wood Blocking", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "2\" Wood Blocking", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "2\" x 6\" x 12''", "Price": 8.99, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 6\" x 12'' Treated", "Price": 14.29, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 8\" x 12''", "Price": 19.78, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 8\" x 12'' Treated", "Price": 17.89, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 10\" x 12''", "Price": 18.12, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 10\" x 12'' Treated", "Price": 23.39, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 12\" x 12''", "Price": 17.95, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 12\" x 12'' Treated", "Price": 29.59, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "1\" x 4\" x 12''", "Price": 13.97, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "1\" x 6\" x 12''", "Price": 11.18, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "1\" x 8\" x 12''", "Price": 13.28, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "1\" x 10\" x 12''", "Price": 18.72, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "1\" x 12\" x 12''", "Price": 18.71, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "5/4 \" x 12''", "Price": 15.08, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 4\" x 12''", "Price": 6.48, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "2\" x 4\" x 12'' Treated", "Price": 10.38, "LaborPerUnit": 0.25, "Labor Rate": 45.0}], "help": "Wood blocking can be selected on the Roof Sections screen. If wood blocking is needed at the perimeter of the roof area at the roof level it will be priced out based on the lineal foot pricing you provide for this list of potential wood blocking options. The program uses a combination of blocking to make up the thickness of underlayment selected. You will have to manually add wood blocking and labor for any get quote or flute filler areas where wood blocking might be required. Provide alternate labor rates if required.", "extras": {}}'::jsonb,0),
  ('non_dl:parapet_wall_blocking','non_dl','Parapet Wall Blocking','{"columns": ["Description", "Price", "LaborPerUnit", "Labor Rate"], "rows": [{"Description": "2\" x 4\" W/ 8\" ISO", "Price": 0.57, "LaborPerUnit": 0.04, "Labor Rate": 40.0}, {"Description": "Tear Off", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Drip Edge 10''", "Price": 9.39, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Ice & Water 66''", "Price": 74.5, "LaborPerUnit": 1, "Labor Rate": 0.0}, {"Description": "Ice & Water HT 66''", "Price": 120.0, "LaborPerUnit": 1, "Labor Rate": 0.0}, {"Description": "Synthetic Underlayment", "Price": 76.5, "LaborPerUnit": 1, "Labor Rate": 0.0}, {"Description": "Starter Shingle 100''", "Price": 55.0, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Shingle ( Per Bundle )", "Price": 41.0, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Ridge Cap 30''", "Price": 75.0, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Ridge Vent 4'' W/Nails", "Price": 14.0, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Coil Nails ( 1 Box 18SQ )", "Price": 51.5, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Valley Metal ( 20\" X 10'' )", "Price": 33.0, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Step Flashing per ft", "Price": 0.75, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Stack Boot", "Price": 22.13, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "1 Tube Black Jack", "Price": 3.26, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Cap Nails", "Price": 33.0, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "Paint", "Price": 8.5, "LaborPerUnit": 0, "Labor Rate": 0.0}], "help": "If wood blocking is needed on top of a parapet wall there are several ways of providing this. If you select wood blocking for parapets in this program, the program will use the pricing you provide here for a combination of a 2x4 fastened to the outside edge of the parapet wall along with filling in the rest of the top of the wall with 1-1/2\" thick polyisocyanurate insulation. If you want to use solid wood blocking you can enter pricing for that in the next green box; however, you will have to override the program each time you select solid wood blocking by deleting lineal footage for default blocking and manually enter lineal footage for alternate wood blocking. This price is per lineal foot. Provide alternate labor rates if required.", "extras": {}}'::jsonb,1),
  ('non_dl:structural_deck_materials','non_dl','Structural Deck Materials','{"columns": ["Description", "Price", "LaborPerUnit", "Labor Rate"], "rows": [{"Description": "Structural Steel", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Plywood Deck ¾\"", "Price": 21.89, "LaborPerUnit": 0.35, "Labor Rate": 45.0}, {"Description": "Plywood Deck 5/8\"", "Price": 21.85, "LaborPerUnit": 0.35, "Labor Rate": 45.0}, {"Description": "Plywood Deck ½\"", "Price": 12.58, "LaborPerUnit": 0.35, "Labor Rate": 45.0}, {"Description": "Tectum 32\" x 96\"", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Tectum Sq Ft", "Price": 4.25, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "1/2 Plywood Treated", "Price": 23.48, "LaborPerUnit": 0.35, "Labor Rate": 45.0}, {"Description": "3/4 Plywood Treated", "Price": 59.99, "LaborPerUnit": 0.35, "Labor Rate": 45.0}, {"Description": "5/8 Plywood Treated", "Price": 53.68, "LaborPerUnit": 0.35, "Labor Rate": 45.0}], "help": "Provide pricing per square foot or per piece for various deck materials, along with alternate rates if required.", "extras": {}}'::jsonb,2),
  ('non_dl:sheet_metal_work','non_dl','Sheet Metal Work','{"columns": ["Description", "Price", "LaborPerUnit", "Labor Rate"], "rows": [{"Description": "Curb Counter Flashing", "Price": 4.0, "LaborPerUnit": 0.0167, "Labor Rate": 45.0}, {"Description": "Reglet Flashing", "Price": 4.3, "LaborPerUnit": 0.25, "Labor Rate": 45.0}, {"Description": "Retro Edge", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Exspansion Joints", "Price": 30.0, "LaborPerUnit": 0.35, "Labor Rate": 45.0}, {"Description": "Inside Miters", "Price": 110.0, "LaborPerUnit": 0.35, "Labor Rate": 45.0}, {"Description": "Outside Miters", "Price": 110.0, "LaborPerUnit": 0.35, "Labor Rate": 45.0}, {"Description": "Flat Coping Cap", "Price": 17.98, "LaborPerUnit": 0.2, "Labor Rate": 45.0}, {"Description": "Snap Coping Cap", "Price": 27.38, "LaborPerUnit": 0.2, "Labor Rate": 45.0}, {"Description": "Canted Coping Cap", "Price": 19.03, "LaborPerUnit": 0.2, "Labor Rate": 45.0}, {"Description": "Reglet Flashing 2-piece", "Price": 9.35, "LaborPerUnit": 0.5, "Labor Rate": 45.0}, {"Description": "White 4 X 10 Sheet", "Price": 209.2, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "3'' Edge Extender", "Price": 3.15, "LaborPerUnit": 0.15, "Labor Rate": 45.0}, {"Description": "4\" Edge Extender & Cleat", "Price": 5.55, "LaborPerUnit": 0.2, "Labor Rate": 45.0}, {"Description": "5\" Edge Extender & Cleat", "Price": 5.75, "LaborPerUnit": 0.2, "Labor Rate": 45.0}, {"Description": "6\" Edge Extender & Cleat", "Price": 6.05, "LaborPerUnit": 0.2, "Labor Rate": 45.0}, {"Description": "7\" Edge Extender & Cleat", "Price": 6.45, "LaborPerUnit": 0.2, "Labor Rate": 45.0}, {"Description": "8\" Edge Extender & Cleat", "Price": 6.75, "LaborPerUnit": 0.2, "Labor Rate": 45.0}, {"Description": "Surface Mt. Counter", "Price": 4.0, "LaborPerUnit": 0.15, "Labor Rate": 45.0}, {"Description": "Duro - Flash per FT", "Price": 6.85, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Parapet Vents Metal", "Price": 160.85, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "ATR Hub 8x8x14", "Price": 374.35, "LaborPerUnit": 0, "Labor Rate": 0.0}, {"Description": "ATR Hub 8x8x30", "Price": 465.2, "LaborPerUnit": 0, "Labor Rate": 0.0}], "help": "The program use counter flashing for one of the terminations on curbs. To complete the program calculation you will need to provide a lineal foot price for counter flashing here. If you have any other sheet metal items you want to have pricing listed on, you can provide that here. Provide alternate labor rates for sheet metal work if required.", "extras": {}}'::jsonb,3),
  ('non_dl:masonry','non_dl','Masonry','{"columns": ["Description", "Price", "LaborPerUnit", "Labor Rate"], "rows": [{"Description": "Remove Only", "Price": 0.0, "LaborPerUnit": 0.1, "Labor Rate": 45.0}, {"Description": "Mortar Mix", "Price": 0.0, "LaborPerUnit": 0.3, "Labor Rate": 45.0}, {"Description": "Replace Capstones", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}], "help": "Please provide the price you pay for mortar mix, per 80lb. bag and the price for any clay tile capstones you might find you need to replace. The program will use the mortar mix price to determine the cost of re-laying capstones on top of a parapet wall. If individual capstones have to replaced you will have to enter a quantity. Provide alternate labor rates if required.", "extras": {}}'::jsonb,4),
  ('non_dl:subcontractors','non_dl','Subcontractors','{"columns": ["Description", "Price", "LaborPerUnit", "Labor Rate"], "rows": [{"Description": "HVAC", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Sheet Metal", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Masonry", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Guttering", "Price": 8.5, "LaborPerUnit": 0, "Labor Rate": 45.0}], "help": "If you have sub-contractors that do work for you on a regular basis and you have standard rates that they charge for work you can enter those rates here, either for an hourly rate or a lineal foot rate, or what ever rate is appropriate. If you have a unit cost for those services or other services you would want to add you can enter them here. Provide alternate labor rates if required.", "extras": {}}'::jsonb,5),
  ('non_dl:3rd_party_services','non_dl','3rd Party Services','{"columns": ["Description", "Price", "LaborPerUnit", "Labor Rate"], "rows": [{"Description": "Crane", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 150.0}, {"Description": "Landfill", "Price": 0.0, "LaborPerUnit": 1, "Labor Rate": 85.0}, {"Description": "Dumpster", "Price": 850.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Vacuum Service", "Price": 30.0, "LaborPerUnit": 0, "Labor Rate": 45.0}, {"Description": "Set Up Charge", "Price": 0.0, "LaborPerUnit": 0, "Labor Rate": 45.0}], "help": "You can provide pricing for various services you use on a regular basis. For the tear off screen you need to provide the program with disposal cost pricing. Please select whether you use roll off units or dump trucks. Then enter the # of yards of materials you can realistically get in your disposal unit. In the pricing column you need to give a price for your disposal cost per roll off unit or dump truck. You could and should include landfill costs unless you want to manually enter this information separately. Provide alternate labor rates if required.", "extras": {"dumpster_or_dump_truck": "Dumpster", "yardage": 30}}'::jsonb,6),
  ('non_dl:preset_custom_applications','non_dl','Preset Custom Applications','{"columns": ["Description", "Price", "LaborPerUnit", "Labor Rate"], "rows": [{"Description": "Plentum Parapet wall vent", "Price": 102.9, "LaborPerUnit": 1.5, "Labor Rate": 45.0}, {"Description": "Standard Roof Hatch", "Price": 978.75, "LaborPerUnit": 10, "Labor Rate": 45.0}, {"Description": "Hatch With Rails", "Price": 1715.62, "LaborPerUnit": 15, "Labor Rate": 45.0}, {"Description": "Straight up Ladder", "Price": 3500.0, "LaborPerUnit": 20, "Labor Rate": 45.0}, {"Description": "Ladder W/ Platform &", "Price": 4200.0, "LaborPerUnit": 30, "Labor Rate": 45.0}], "help": "If you have a custom application you provide to your customers and you have a unit cost for that application you can enter that rate here. The rate will show up under Customized Contractor Applications in the bid program. Provide alternate labor rates if required.", "extras": {}}'::jsonb,7)
) v(id, branch, category, data, sort)
where not exists (select 1 from public.pricing_catalog where branch='non_dl');
