-- Phase 2 (part 2e): Accessory Labor (14 categories, varying column shapes; jsonb).
-- Idempotent. RLS: authenticated read, admin-only write.

create table if not exists public.accessory_labor (
  id text primary key,
  category text not null,
  data jsonb not null default '{}'::jsonb,
  sort integer not null default 0
);
alter table public.accessory_labor enable row level security;
revoke all on public.accessory_labor from anon;
drop policy if exists accessory_labor_read on public.accessory_labor;
create policy accessory_labor_read on public.accessory_labor for select to authenticated using (true);
drop policy if exists accessory_labor_write on public.accessory_labor;
create policy accessory_labor_write on public.accessory_labor for all to authenticated using (public.is_admin()) with check (public.is_admin());
insert into public.accessory_labor (id, category, data, sort)
select * from (values
  ('accessory_others','Accessory Others','{"columns": ["Description", "Labor(Hrs)"], "rows": [{"Description": "30\" x 60\" White - Walk Pad", "Labor(Hrs)": 0.5}, {"Description": "60\" x 60\" White - Walk Pad", "Labor(Hrs)": 0.5}, {"Description": "30\" x 60\" Gray - Walk Pad", "Labor(Hrs)": 0.5}, {"Description": "60\" x 60\" Gray - Walk Pad", "Labor(Hrs)": 0.5}, {"Description": "30\" x 60\" Safety - Walk Pad", "Labor(Hrs)": 0.5}, {"Description": "60\" x 60\" Safety - Walk Pad", "Labor(Hrs)": 0.5}, {"Description": "White Parapet Wall Vent", "Labor(Hrs)": 0.5}, {"Description": "Tan Parapet Wall Vent", "Labor(Hrs)": 0.5}, {"Description": "Gray Parapet Wall Vent", "Labor(Hrs)": 0.5}, {"Description": "30\" x 60\" Tan - Walk Pad", "Labor(Hrs)": 0.5}, {"Description": "60\" x 60\" Tan - Walk Pad", "Labor(Hrs)": 0.5}, {"Description": "30\"X 60\" Safety Fully Skirted Walk Pad", "Labor(Hrs)": 0.65}, {"Description": "30\"X 60\" White Fully Skirted Walk Pad", "Labor(Hrs)": 0.65}]}'::jsonb,0),
  ('corners','Corners','{"columns": ["Description", "Labor(Hrs)"], "rows": [{"Description": "Inside 6\" x 6\"", "Labor(Hrs)": 0.1667}, {"Description": "Inside 6\" x 18\"", "Labor(Hrs)": 0.1667}, {"Description": "Outside 6\" x 6\"", "Labor(Hrs)": 0.1667}, {"Description": "Outside 6\" x 18\"", "Labor(Hrs)": 0.2222}, {"Description": "Outside 18\" x 12\"", "Labor(Hrs)": 0.3333}, {"Description": "Outside Butterfly 6\" x 6\"", "Labor(Hrs)": 0.2222}]}'::jsonb,1),
  ('drain_boots','Drain Boots','{"columns": ["Description", "Labor(Hrs)"], "rows": [{"Description": "2\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "2½\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "3\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "3½\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "4\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "4½\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "5\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "5½\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "6\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "6½\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "7\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "7½\" Drain Boot", "Labor(Hrs)": 0.5}, {"Description": "8\" Drain Boot", "Labor(Hrs)": 0.5}]}'::jsonb,2),
  ('drain_roof_types','Drain Roof Types','{"columns": ["Description", "Area Prep Labor(Hrs)", "Reinstallation Labor (Hrs)"], "rows": [{"Description": "None", "Area Prep Labor(Hrs)": 0, "Reinstallation Labor (Hrs)": 0.25}, {"Description": "Single Ply", "Area Prep Labor(Hrs)": 0.25, "Reinstallation Labor (Hrs)": 0.25}, {"Description": "BUR", "Area Prep Labor(Hrs)": 0.5, "Reinstallation Labor (Hrs)": 0.5}, {"Description": "GS BUR", "Area Prep Labor(Hrs)": 0.75, "Reinstallation Labor (Hrs)": 0.75}]}'::jsonb,3),
  ('drip_edges','Drip Edges','{"columns": ["Description", "Labor(Hrs)"], "rows": [{"Description": "Drip Edge 2\"", "Labor(Hrs)": 0.0275}, {"Description": "Drip Edge 2\" Corner", "Labor(Hrs)": 0.2}, {"Description": "Drip Edge 4\"", "Labor(Hrs)": 0.0275}, {"Description": "Drip Edge 4\" Corner", "Labor(Hrs)": 0.2}]}'::jsonb,4),
  ('fascia_bars','Fascia Bars','{"columns": ["Description", "PreDrill Labor(Hrs)", "NoDrill Labor (Hrs)"], "rows": [{"Description": "1¾\" Fascia Bar", "PreDrill Labor(Hrs)": 0.0374, "NoDrill Labor (Hrs)": 0.0187}, {"Description": "4\" Fascia Bar", "PreDrill Labor(Hrs)": 0.0395, "NoDrill Labor (Hrs)": 0.0197}]}'::jsonb,5),
  ('gravel_stops','Gravel Stops','{"columns": ["Description", "NoDrill Labor (Hrs)"], "rows": [{"Description": "Gravel Stop 2\"", "NoDrill Labor (Hrs)": 0.0275}, {"Description": "Gravel Stop 2\" Corner", "NoDrill Labor (Hrs)": 0.2}, {"Description": "Gravel Stop 4\"", "NoDrill Labor (Hrs)": 0.0275}, {"Description": "Gravel Stop 4\" Corner", "NoDrill Labor (Hrs)": 0.2}]}'::jsonb,6),
  ('membrane_accs','Membrane Accs','{"columns": ["Description", "Labor (Hrs)"], "rows": [{"Description": "ARP (SqFt)", "Labor (Hrs)": 0}, {"Description": "T-Patch", "Labor (Hrs)": 0.1}, {"Description": "1'' of Stripping w/ 6\"oc Fasteners", "Labor (Hrs)": 0.04}]}'::jsonb,7),
  ('pipe_stack_usages','Pipe Stack Usages','{"columns": ["Description", "Multiplier"], "rows": [{"Description": "Plumbing", "Multiplier": 0.5}, {"Description": "Hot Stack", "Multiplier": 1}, {"Description": "Pitch Pan", "Multiplier": 1.5}]}'::jsonb,8),
  ('strainers','Strainers','{"columns": ["Description", "Labor(Hrs)"], "rows": [{"Description": "3\" - 4\" PVC Drains", "Labor(Hrs)": 0}, {"Description": "3\"-5\" Black Leaf Grates", "Labor(Hrs)": 0.25}, {"Description": "Dome Strainer", "Labor(Hrs)": 0.5}, {"Description": "2\" Drain Adapter", "Labor(Hrs)": 0.25}]}'::jsonb,9),
  ('termination_bars','Termination Bars','{"columns": ["Description", "PreDrill Labor(Hrs)", "NoDrill Labor (Hrs)"], "rows": [{"Description": "Term Bar", "PreDrill Labor(Hrs)": 0.035, "NoDrill Labor (Hrs)": 0.0175}]}'::jsonb,10),
  ('two_piece_metals','Two Piece Metals','{"columns": ["Description", "Labor (Hr/Ft)", "Corner Labor(Hr/Piece)"], "rows": [{"Description": "3\" 2-Piece Compression", "Labor (Hr/Ft)": 0.043, "Corner Labor(Hr/Piece)": 0.2}, {"Description": "4\" 2-Piece Compression", "Labor (Hr/Ft)": 0.043, "Corner Labor(Hr/Piece)": 0.2}, {"Description": "5\" 2-Piece Compression", "Labor (Hr/Ft)": 0.043, "Corner Labor(Hr/Piece)": 0.2}, {"Description": "6\" 2-Piece Compression", "Labor (Hr/Ft)": 0.043, "Corner Labor(Hr/Piece)": 0.2}, {"Description": "7\" 2-Piece Compression", "Labor (Hr/Ft)": 0.043, "Corner Labor(Hr/Piece)": 0.2}, {"Description": "8\" 2-Piece Compression", "Labor (Hr/Ft)": 0.043, "Corner Labor(Hr/Piece)": 0.2}]}'::jsonb,11),
  ('vents','Vents','{"columns": ["Description", "Labor(Hrs)"], "rows": [{"Description": "Vents", "Labor(Hrs)": 0.5}]}'::jsonb,12),
  ('washers','Washers','{"columns": ["Description", "Labor(Hrs)"], "rows": [{"Description": "1/2\" Conduit Washer", "Labor(Hrs)": 0.3333}, {"Description": "3/4\" Conduit Washer", "Labor(Hrs)": 0.3333}, {"Description": "1\" Conduit Washer", "Labor(Hrs)": 0.3333}]}'::jsonb,13)
+) v(id, category, data, sort)
where not exists (select 1 from public.accessory_labor);
