-- Phase 2 (part 2c): Roof Deck Labor - Membrane Labor tab (per roof-system x attachment).
-- Data stored as jsonb per combo because the legacy structures differ by system.
-- Idempotent. RLS: authenticated read, admin-only write.

create table if not exists public.rdl_combos (
  id uuid primary key default gen_random_uuid(),
  roof_system text not null,
  attachment text not null,
  formula text,
  data jsonb not null default '{}'::jsonb,
  sort integer not null default 0,
  unique (roof_system, attachment)
);
alter table public.rdl_combos enable row level security;
revoke all on public.rdl_combos from anon;
drop policy if exists rdl_combos_read on public.rdl_combos;
create policy rdl_combos_read on public.rdl_combos for select to authenticated using (true);
drop policy if exists rdl_combos_write on public.rdl_combos;
create policy rdl_combos_write on public.rdl_combos for all to authenticated using (public.is_admin()) with check (public.is_admin());
insert into public.rdl_combos (roof_system, attachment, formula, data, sort)
select * from (values
  ('Duro-Last','mechanical','Mechanical Labor = 10 Hrs x Deck Type Multi x Tab Spacing Multi x Fastener Spacing Multi x Sheet Size x Thickness','{"base": {"tab_or_width_label": "Tab", "tab_value": 28, "tab_multiplier": 1.5125}, "deck_multipliers": {"Wood": 1, "Steel": 1.064, "Retrofit": 1.25, "Concrete": 2, "Gypsum": 1.8, "LWC/Steel": 1.2, "LWC/Concrete": 2.3, "LWC/Other": 1.52, "Tectum": 1.064, "Purlin": 1.2}, "fastener_spacing_multipliers": [{"spacing_in": 24, "multiplier": 0.91}, {"spacing_in": 21, "multiplier": 0.96}, {"spacing_in": 18, "multiplier": 1}, {"spacing_in": 15, "multiplier": 1.04}, {"spacing_in": 12, "multiplier": 1.1}, {"spacing_in": 9, "multiplier": 1.21}, {"spacing_in": 6, "multiplier": 1.41}], "complexity_factors": null, "sheet_size_multipliers": [{"label": "Roll Good", "roof_section": 4, "underlayment": 4}, {"label": "500 sf", "roof_section": 2.4, "underlayment": 2.4}, {"label": "1000 sf", "roof_section": 1.2, "underlayment": 1.2}, {"label": "1500 sf", "roof_section": 1, "underlayment": 1}, {"label": "2000 sf", "roof_section": 0.98, "underlayment": 0.98}, {"label": "2500 sf", "roof_section": 0.9, "underlayment": 0.9}, {"label": "3000 sf", "roof_section": 0.82, "underlayment": 0.82}], "sheet_size_label": "Mechanical Sheet Size Labor Multiplier", "thickness_multipliers": [{"mil": 40, "multiplier": 1}, {"mil": 50, "multiplier": 1.15}, {"mil": 60, "multiplier": 1.25}], "adhesive": null, "notes": "Canonical 10-column mechanical model. Base 10 hrs is per 2500 sf (engine adds /2500). This is the combo the engine-truth worked anchor uses: Wood@18in = 10*1*1.5125*1 = 15.13 hrs."}'::jsonb,0),
  ('Duro-Roof','mechanical','Mechanical Labor = 10 Hrs x Deck Type Multi x Tab Spacing Multi x Fastener Spacing Multi x Sheet Size x Thickness','{"base": {"tab_or_width_label": "Tab", "tab_value": 57, "tab_multiplier": 1.25}, "deck_multipliers": {"Wood": 1, "Steel": 1.064, "Retrofit": 1.25, "Concrete": 2, "Gypsum": 1.8, "LWC/Steel": 1.2, "LWC/Concrete": 2.3, "LWC/Other": 1.52, "Tectum": 1.064, "Purlin": 1.2}, "fastener_spacing_multipliers": [{"spacing_in": 24, "multiplier": 0.91}, {"spacing_in": 21, "multiplier": 0.96}, {"spacing_in": 18, "multiplier": 1}, {"spacing_in": 15, "multiplier": 1.04}, {"spacing_in": 12, "multiplier": 1.1}, {"spacing_in": 9, "multiplier": 1.21}, {"spacing_in": 6, "multiplier": 1.41}], "complexity_factors": null, "sheet_size_multipliers": [{"label": "500 sf", "roof_section": 2.4, "underlayment": 2.4}, {"label": "1000 sf", "roof_section": 1.2, "underlayment": 1.2}, {"label": "1500 sf", "roof_section": 1, "underlayment": 1}, {"label": "2000 sf", "roof_section": 0.98, "underlayment": 0.98}, {"label": "2500 sf", "roof_section": 0.9, "underlayment": 0.9}, {"label": "3000 sf", "roof_section": 0.82, "underlayment": 0.82}], "sheet_size_label": "Mechanical Sheet Size Labor Multiplier", "thickness_multipliers": [{"mil": 40, "multiplier": 1}, {"mil": 50, "multiplier": 1.15}, {"mil": 60, "multiplier": 1.25}], "adhesive": null, "notes": "Same 10-column mechanical model as Duro-Last but Tab=57 / TabMultiplier=1.25. No ''Roll Good'' row in sheet-size grid (6 rows starting at 500 sf). Engine applies a non-versioned DuroRoof x1.05 surcharge on final MEMBRANE COST (not on labor) per engine-truth sec 1 — that surcharge is not part of this labor tab."}'::jsonb,2),
  ('Duro-Tuff','mechanical','Mechanical Labor = 10 Hrs x Deck Type Multi x Roll Width Multi x Fastener Spacing Multi x Complexity x Thickness','{"base": {"tab_or_width_label": "Width", "tab_value": 30, "tab_multiplier": 2.8}, "deck_multipliers": {"Wood": 1, "Steel": 1.064, "Retrofit": 1.25, "Concrete": 2, "Gypsum": 1.8, "LWC/Steel": 1.2, "LWC/Concrete": 2.3, "LWC/Other": 1.52, "Tectum": 1.064, "Purlin": 1.2}, "fastener_spacing_multipliers": [{"spacing_in": 24, "multiplier": 0.91}, {"spacing_in": 21, "multiplier": 0.96}, {"spacing_in": 18, "multiplier": 1}, {"spacing_in": 15, "multiplier": 1.04}, {"spacing_in": 12, "multiplier": 1.1}, {"spacing_in": 9, "multiplier": 1.21}, {"spacing_in": 6, "multiplier": 1.41}], "complexity_factors": [{"label": "Open", "value": 0.9}, {"label": "Minor", "value": 0.98}, {"label": "Moderate", "value": 1}, {"label": "Medium", "value": 1.2}, {"label": "Heavy", "value": 2.4}, {"label": "Extreme", "value": 4}], "sheet_size_multipliers": null, "thickness_multipliers": [{"mil": 50, "multiplier": 1.15}, {"mil": 60, "multiplier": 1.25}], "adhesive": null, "notes": "Duro-Tuff mechanical differs from Duro-Last/Duro-Roof: base labeled ''Width'' (=30) with ''Tab Multiplier''=2.8 (roll-width model, not tab). Section 2 is COMPLEXITY FACTORS (not sheet size). No 40mil thickness row (starts at 50mil). Deck multiplier row and fastener-spacing multipliers are identical to the standard 10-column set."}'::jsonb,4),
  ('Duro-Bond','mechanical','Mechanical Labor = Sheet Layout + Fastener Time(min/fastener) (x Qty Fasteners) x Sheet Size x Thickness','{"base": {"sheet_layout_hours": 10, "note": "This screen has NO tab/width option and NO deck-multiplier row; the base labor grid is structured differently (see structure below)."}, "duro_bond_base_labor": {"sheet_layout_hr": 10, "single_fastener_time_min_per_fastener_by_deck": {"Wood": 0.342, "Steel": 0.462, "Retrofit": 0.462, "Concrete": 2.185, "LWC/Steel": 0.858, "LWC/Concrete": 2.185, "Purlin": 0.462}, "deck_column_order": ["Wood", "Steel", "Retrofit", "Concrete", "LWC/Steel", "LWC/Concrete", "Purlin"], "fastener_density_rows_computed_only": [20, 18, 16, 14, 12, 10, 8, 6], "_density_note": "Column header ''Fasteners / 32 SqFt''. The 8 density rows (20..6) and their per-deck cells are COMPUTED preview values, not editable inputs — not stored. Editable inputs are: Sheet Layout(Hr)=10 and the single-fastener-time (min/fastener) row per deck type."}, "deck_multipliers": null, "fastener_spacing_multipliers": null, "complexity_factors": null, "sheet_size_multipliers": [{"label": "500 sf", "roof_section": 2, "underlayment": 2.4}, {"label": "1000 sf", "roof_section": 1.1, "underlayment": 1.2}, {"label": "1500 sf", "roof_section": 1, "underlayment": 1}, {"label": "2000 sf", "roof_section": 1.1, "underlayment": 0.98}, {"label": "2500 sf", "roof_section": 1.2, "underlayment": 0.9}], "sheet_size_label": "Mechanical Sheet Size Labor Multiplier", "thickness_multipliers": [{"mil": 40, "multiplier": 1}, {"mil": 50, "multiplier": 1.15}, {"mil": 60, "multiplier": 1.25}], "adhesive": null, "notes": "GENUINELY DIFFERENT MODEL. Per engine-truth sec 3.4: hours = memb * (LayoutTime/2500) * thicknessLabor * (SheetSize.MechSheetMulti only in FormulasVersion _237) + (#fasteners in section) * SingleFastenerTimeByDeck[deck]. Editable admin inputs are: LayoutTime (=Sheet Layout Hr = 10) and the per-deck SingleFastenerTime (min/fastener) row. Deck set is REDUCED to 7 columns (Wood, Steel, Retrofit, Concrete, LWC/Steel, LWC/Concrete, Purlin) — NO Gypsum, LWC/Other, or Tectum columns unlike the standard 10-col systems. Sheet-size grid has only 5 rows (no Roll Good, no 3000 sf) and RoofSection multipliers differ from the standard set (2 / 1.1 / 1 / 1.1 / 1.2). A ''Preview Times'' button appears below the base grid on this variant."}'::jsonb,6),
  ('Duro-Last','adhesive','Adhesive Labor = Base Labor x Sheet Size x Thickness','{"base": null, "deck_multipliers": null, "fastener_spacing_multipliers": null, "complexity_factors": null, "sheet_size_multipliers": [{"label": "Roll Good", "roof_section": 4, "underlayment": null}, {"label": "500 sf", "roof_section": 2.4, "underlayment": null}, {"label": "1000 sf", "roof_section": 1.2, "underlayment": null}, {"label": "1500 sf", "roof_section": null, "underlayment": null}, {"label": "2000 sf", "roof_section": null, "underlayment": null}, {"label": "2500 sf", "roof_section": null, "underlayment": null}, {"label": "3000 sf", "roof_section": null, "underlayment": null}], "sheet_size_label": "Adhesive Sheet Size Labor Multiplier", "thickness_multipliers": [{"mil": 40, "multiplier": 1}, {"mil": 50, "multiplier": 1.15}, {"mil": 60, "multiplier": 1.25}], "adhesive": {"base_hours_per_1000_sqft_by_substrate": [{"substrate": "Water Based Adhesive", "labor_per_1000_sqft": 5.215}, {"substrate": "Solvent Based Adhesive", "labor_per_1000_sqft": 6.95}]}, "notes": "Adhesive model (engine-truth sec 3.3): rate = baseHrs/1000 * (rollGoodWidthMulti for roll goods OR SheetSize.SmartSheetMulti) * complexity; +20% perimeter bump and corner=perimeter are code constants. Section 2 is titled ''Adhesive Sheet Size Labor Multiplier''; the Underlayment multiplier column is entirely BLANK/empty for this combo, and only the first three rows (Roll Good 4, 500sf 2.4, 1000sf 1.2) carry RoofSection values — rows 1500sf-3000sf are blank (blank = use default). No Complexity Factors table on the Duro-Last adhesive variant (Duro-Tuff/Duro-Fleece adhesive DO show complexity)."}'::jsonb,1),
  ('Duro-Tuff','adhesive','Adhesive Labor = Base Labor x Complexity x Thickness','{"base": null, "deck_multipliers": null, "fastener_spacing_multipliers": null, "complexity_factors": [{"label": "Open", "value": 0.9}, {"label": "Minor", "value": 0.98}, {"label": "Moderate", "value": 1}, {"label": "Medium", "value": 1.2}, {"label": "Heavy", "value": 2.4}, {"label": "Extreme", "value": 4}], "sheet_size_multipliers": null, "thickness_multipliers": [{"mil": 50, "multiplier": 1.15}, {"mil": 60, "multiplier": 1.25}], "adhesive": {"base_hours_per_1000_sqft_by_substrate": [{"substrate": "Water Based Adhesive", "labor_per_1000_sqft": 5.215}, {"substrate": "Solvent Based Adhesive", "labor_per_1000_sqft": 6.95}]}, "notes": "Duro-Tuff adhesive uses Complexity (not Sheet Size) as section 2 — same complexity table as Duro-Tuff mechanical. No 40mil thickness row (50mil/60mil only). Base substrate labor same 5.215 / 6.95 as Duro-Last adhesive."}'::jsonb,5),
  ('Duro-Fleece','adhesive','Adhesive Labor = Base Labor x Complexity x Thickness','{"base": null, "deck_multipliers": null, "fastener_spacing_multipliers": null, "complexity_factors": [{"label": "Open", "value": 0.9}, {"label": "Minor", "value": 0.98}, {"label": "Moderate", "value": 1}, {"label": "Medium", "value": 1.2}, {"label": "Heavy", "value": 2.4}, {"label": "Extreme", "value": 4}], "sheet_size_multipliers": null, "thickness_multipliers": [{"mil": 50, "multiplier": 1.15}, {"mil": "50 Plus", "multiplier": 1.15}, {"mil": 60, "multiplier": 1.25}, {"mil": "60 Plus", "multiplier": 1.25}], "adhesive": {"base_hours_per_1000_sqft_by_substrate": [{"substrate": "Water Based Adhesive", "labor_per_1000_sqft": 5.215}, {"substrate": "Duro-Fleece Adhesive(2-boxes)", "labor_per_1000_sqft": 5.215}, {"substrate": "Duro-Fleece Adhesive(cartridge)", "labor_per_1000_sqft": 5.215}, {"substrate": "Duro-Grip Adhesive(CR-20)", "labor_per_1000_sqft": 5.8408}, {"substrate": "OlyBond500 Bag-in-Box", "labor_per_1000_sqft": 5.215}, {"substrate": "OlyBond500 SpotShot", "labor_per_1000_sqft": 5.215}]}, "notes": "Duro-Fleece adhesive has the RICHEST base-labor substrate list (6 adhesive types incl. Duro-Fleece-specific 2-box/cartridge and Duro-Grip CR-20 at 5.8408). Complexity section 2 (same table as Duro-Tuff). Thickness table has 4 rows incl. ''50mil Plus'' (1.15) and ''60mil Plus'' (1.25) variants — unique to Duro-Fleece among captured combos. On-screen label still literally reads ''Mechanical Labor ='' even under Adhesive Attachment (app quirk)."}'::jsonb,9)
) v(roof_system, attachment, formula, data, sort)
where not exists (select 1 from public.rdl_combos);
